[workspace]
authors = ["TheSkyentist <raphael.hviding@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "04_slurm_cluster"
platforms = ["osx-64","osx-arm64","linux-64","win-64"]
version = "0.1.0"

[dependencies]
snakemake = ">=9.3.0,<10"
snakemake-executor-plugin-slurm = ">=1.1.0,<2"
graphviz = ">=12.2.1,<13"